### ISSUE TITLE
Got "Internal Server Error" when click example data file 'bpmc3k.h5ad'

### ISSUE THREAD

**Issue by huihai828** [mestia/cellxgene-proxy-docker-demo#1]
When click data file 'bpmc3k.h5ad', got server error "The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application."
In server side, the error traceback is as follows:
File "/usr/local/lib/python3.9/site-packages/cellxgene_gateway/cache_entry.py", line 193, in serve_content
cellxgene-grp1           |     cellxgene_response.content.decode()
cellxgene-grp1           | UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb5 in position 1: invalid start byte

**Comment by mestia** [comment]
Hey, are you sure that the file h5ad file is not damaged? The error looks like cellxgene backend issue.
Do you get the front page from the container?

**Comment by huihai828** [comment]
I tried a different cellxgene-gateway Docker image, and it worked.

**Comment by mestia** [comment]
The problem suppose to be fixed with the updated versionof  cellxgene-fateway docker instance.
